//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.26 at 03:31:55 PM ART 
//

package ar.com.santanderrio.obp.servicios.monedero.entities;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Resultado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Paginacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Datos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Dato" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ObtenerTransaccionesTagDataResponse">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ID_Trx" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                       &lt;element name="Fecha" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Tipo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Estado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Importe" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="Lugar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Orden" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "resultado", "paginacion", "datos" })
@XmlRootElement(name = "Respuesta")
public class RespuestaTransaccionesTag {

	/** The resultado. */
	@XmlElement(name = "Resultado", required = true)
	protected String resultado;

	/** The paginacion. */
	@XmlElement(name = "Paginacion", required = true)
	protected String paginacion;

	/** The datos. */
	@XmlElement(name = "Datos", required = true)
	protected RespuestaTransaccionesTag.Datos datos;

	/**
	 * Gets the value of the resultado property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResultado() {
		return resultado;
	}

	/**
	 * Sets the value of the resultado property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResultado(String value) {
		this.resultado = value;
	}

	/**
	 * Gets the value of the paginacion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaginacion() {
		return paginacion;
	}

	/**
	 * Sets the value of the paginacion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPaginacion(String value) {
		this.paginacion = value;
	}

	/**
	 * Gets the value of the datos property.
	 * 
	 * @return possible object is {@link RespuestaTransaccionesTag.Datos }
	 * 
	 */
	public RespuestaTransaccionesTag.Datos getDatos() {
		return datos;
	}

	/**
	 * Sets the value of the datos property.
	 * 
	 * @param value
	 *            allowed object is {@link RespuestaTransaccionesTag.Datos }
	 * 
	 */
	public void setDatos(RespuestaTransaccionesTag.Datos value) {
		this.datos = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Dato" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="ObtenerTransaccionesTagDataResponse">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="ID_Trx" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *                             &lt;element name="Fecha" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="Tipo" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="Estado" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="Importe" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                             &lt;element name="Lugar" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="Orden" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "dato" })
	public static class Datos {

		/** The dato. */
		@XmlElement(name = "Dato")
		protected List<RespuestaTransaccionesTag.Datos.Dato> dato;

		/**
		 * Gets the value of the dato property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the dato property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getDato().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link RespuestaTransaccionesTag.Datos.Dato }
		 *
		 * @return the dato
		 */
		public List<RespuestaTransaccionesTag.Datos.Dato> getDato() {
			if (dato == null) {
				dato = new ArrayList<RespuestaTransaccionesTag.Datos.Dato>();
			}
			return this.dato;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="ObtenerTransaccionesTagDataResponse">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="ID_Trx" type="{http://www.w3.org/2001/XMLSchema}short"/>
		 *                   &lt;element name="Fecha" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="Tipo" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="Estado" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="Importe" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *                   &lt;element name="Lugar" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="Orden" type="{http://www.w3.org/2001/XMLSchema}short"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "obtenerTransaccionesTagDataResponse" })
		public static class Dato {

			/** The obtener transacciones tag data response. */
			@XmlElement(name = "ObtenerTransaccionesTagDataResponse", required = true)
			protected RespuestaTransaccionesTag.Datos.Dato.ObtenerTransaccionesTagDataResponse obtenerTransaccionesTagDataResponse;

			/**
			 * Gets the value of the obtenerTransaccionesTagDataResponse
			 * property.
			 * 
			 * @return possible object is
			 *         {@link RespuestaTransaccionesTag.Datos.Dato.ObtenerTransaccionesTagDataResponse }
			 * 
			 */
			public RespuestaTransaccionesTag.Datos.Dato.ObtenerTransaccionesTagDataResponse getObtenerTransaccionesTagDataResponse() {
				return obtenerTransaccionesTagDataResponse;
			}

			/**
			 * Sets the value of the obtenerTransaccionesTagDataResponse
			 * property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link RespuestaTransaccionesTag.Datos.Dato.ObtenerTransaccionesTagDataResponse }
			 * 
			 */
			public void setObtenerTransaccionesTagDataResponse(
					RespuestaTransaccionesTag.Datos.Dato.ObtenerTransaccionesTagDataResponse value) {
				this.obtenerTransaccionesTagDataResponse = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="ID_Trx" type="{http://www.w3.org/2001/XMLSchema}short"/>
			 *         &lt;element name="Fecha" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="Tipo" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="Estado" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="Importe" type="{http://www.w3.org/2001/XMLSchema}float"/>
			 *         &lt;element name="Lugar" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="Orden" type="{http://www.w3.org/2001/XMLSchema}short"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "idTrx", "fecha", "tipo", "estado", "importe", "lugar", "orden" })
			public static class ObtenerTransaccionesTagDataResponse {

				/** The id trx. */
				@XmlElement(name = "ID_Trx")
				protected short idTrx;

				/** The fecha. */
				@XmlElement(name = "Fecha", required = true)
				protected String fecha;

				/** The tipo. */
				@XmlElement(name = "Tipo", required = true)
				protected String tipo;

				/** The estado. */
				@XmlElement(name = "Estado", required = true)
				protected String estado;

				/** The importe. */
				@XmlElement(name = "Importe")
				protected float importe;

				/** The lugar. */
				@XmlElement(name = "Lugar", required = true)
				protected String lugar;

				/** The orden. */
				@XmlElement(name = "Orden")
				protected short orden;

				/**
				 * Gets the value of the idTrx property.
				 *
				 * @return the ID trx
				 */
				public short getIDTrx() {
					return idTrx;
				}

				/**
				 * Sets the value of the idTrx property.
				 *
				 * @param value
				 *            the new ID trx
				 */
				public void setIDTrx(short value) {
					this.idTrx = value;
				}

				/**
				 * Gets the value of the fecha property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getFecha() {
					return fecha;
				}

				/**
				 * Sets the value of the fecha property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setFecha(String value) {
					this.fecha = value;
				}

				/**
				 * Gets the value of the tipo property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getTipo() {
					return tipo;
				}

				/**
				 * Sets the value of the tipo property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setTipo(String value) {
					this.tipo = value;
				}

				/**
				 * Gets the value of the estado property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getEstado() {
					return estado;
				}

				/**
				 * Sets the value of the estado property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setEstado(String value) {
					this.estado = value;
				}

				/**
				 * Gets the value of the importe property.
				 *
				 * @return the importe
				 */
				public float getImporte() {
					return importe;
				}

				/**
				 * Sets the value of the importe property.
				 *
				 * @param value
				 *            the new importe
				 */
				public void setImporte(float value) {
					this.importe = value;
				}

				/**
				 * Gets the value of the lugar property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getLugar() {
					return lugar;
				}

				/**
				 * Sets the value of the lugar property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setLugar(String value) {
					this.lugar = value;
				}

				/**
				 * Gets the value of the orden property.
				 *
				 * @return the orden
				 */
				public short getOrden() {
					return orden;
				}

				/**
				 * Sets the value of the orden property.
				 *
				 * @param value
				 *            the new orden
				 */
				public void setOrden(short value) {
					this.orden = value;
				}

			}

		}

	}

}
