//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.06 at 11:52:03 PM ART 
//

package ar.com.santanderrio.obp.servicios.scomp.client.domain;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Cbu" type="{}notempty"/>
 *         &lt;element name="TitularCtaDestino" type="{}notempty"/>
 *         &lt;element name="IdBeneficiario" type="{}id-numeric-large-ne"/>
 *         &lt;element name="CaracteristicaCtaDestino" type="{}id-numeric-large-ne"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlType
public class DestinoTrfcci extends Destino {

    /** The id beneficiario. */
    @XmlElement(name = "IdBeneficiario")
    protected String idBeneficiario;

    /** The caracteristica cta destino. */
    @XmlElement(name = "CaracteristicaCtaDestino")
    protected String caracteristicaCtaDestino;

    /**
     * Gets the value of the idBeneficiario property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdBeneficiario() {
        return idBeneficiario;
    }

    /**
     * Sets the value of the idBeneficiario property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIdBeneficiario(String value) {
        this.idBeneficiario = value;
    }

    /**
     * Gets the value of the caracteristicaCtaDestino property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaracteristicaCtaDestino() {
        return caracteristicaCtaDestino;
    }

    /**
     * Sets the value of the caracteristicaCtaDestino property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCaracteristicaCtaDestino(String value) {
        this.caracteristicaCtaDestino = value;
    }

}
