//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 12:45:55 PM ART 
//

package ar.com.santanderrio.obp.servicios.scomp.client.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Cbu" type="{}notempty"/>
 *         &lt;element name="IdBeneficiario" type="{}id-numeric-large-ne"/>
 *         &lt;element name="CaracteristicaCtaDestino" type="{}id-numeric-large-ne"/>
 *         &lt;element name="TitularCtaDestino" type="{}notempty"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlSeeAlso({ DestinoTrfcci.class, DestinoPaghabcci.class, DestinoTrfcta.class })
public class Destino {

    /** The cbu. */
    @XmlElement(name = "Cbu", required = true)
    protected String cbu;

    /** The titular cta destino. */
    @XmlElement(name = "TitularCtaDestino", required = true)
    protected String titularCtaDestino;

    /**
     * Gets the value of the cbu property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCbu() {
        return cbu;
    }

    /**
     * Sets the value of the cbu property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCbu(String value) {
        this.cbu = value;
    }

    /**
     * Gets the value of the titularCtaDestino property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTitularCtaDestino() {
        return titularCtaDestino;
    }

    /**
     * Sets the value of the titularCtaDestino property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTitularCtaDestino(String value) {
        this.titularCtaDestino = value;
    }

}
