//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 12:45:55 PM ART 
//

package ar.com.santanderrio.obp.servicios.scomp.client.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="TipoCuentaOrigen" type="{}cuenta-tipo"/>
 *         &lt;element name="SucursalCuentaOrigen" type="{}sucursal-nro"/>
 *         &lt;element name="NumeroCuentaOrigen" type="{}cuenta-nro"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Origen")
public class Origen {

    /** The tipo cuenta origen. */
    @XmlElement(name = "TipoCuentaOrigen")
    protected String tipoCuentaOrigen;

    /** The sucursal cuenta origen. */
    @XmlElement(name = "SucursalCuentaOrigen")
    protected String sucursalCuentaOrigen;

    /** The numero cuenta origen. */
    @XmlElement(name = "NumeroCuentaOrigen")
    protected String numeroCuentaOrigen;

    /**
     * Gets the value of the tipoCuentaOrigen property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTipoCuentaOrigen() {
        return tipoCuentaOrigen;
    }

    /**
     * Sets the value of the tipoCuentaOrigen property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTipoCuentaOrigen(String value) {
        this.tipoCuentaOrigen = value;
    }

    /**
     * Gets the value of the sucursalCuentaOrigen property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSucursalCuentaOrigen() {
        return sucursalCuentaOrigen;
    }

    /**
     * Sets the value of the sucursalCuentaOrigen property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSucursalCuentaOrigen(String value) {
        this.sucursalCuentaOrigen = value;
    }

    /**
     * Gets the value of the numeroCuentaOrigen property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumeroCuentaOrigen() {
        return numeroCuentaOrigen;
    }

    /**
     * Sets the value of the numeroCuentaOrigen property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNumeroCuentaOrigen(String value) {
        this.numeroCuentaOrigen = value;
    }

}
