package ar.com.santanderrio.obp.servicios.transferencias.entities.metricas;

public enum DetalleError {

    RSA_GENERIC_ERROR("RSA_0000"),
    RSA_OFFLINE("RSA_0001"),
    RSA_OFFLINE_VALIDACION_FALLIDA("RSA_0001_001"),
    RSA_DENY_TRANSFERENCIA_BLACK_LIST("RSA_0002"),
    RSA_USUARIO_BLOQUEADO("RSA_0003"),
    RSA_TRANSFERENCIA_RIESGO_ALTO("RSA_0004"),
    CVU_DOLARES_NO_HABILITADO("CVU_USD_INHAB_0000"),
    IMPORTE_LIMITE_TRANSFERENCIA("IMP_LIM_0000"),
    SALDO_INSUFICIENTE("SALDO_INSUF_0000"),
    HOST_TIMEOUT("HOST_TIMEOUT_0000"),
    TRANSFERENCIA_DOLARES_INHABILITADA("TRANSF_USD_INHAB_0000"),
    CUENTA_SIN_OPERAR("CTA_0001"),
    CUENTA_CERRADA("CTA_0002"),
    CUENTA_SIN_DEBITOS_NI_ACREDITACIONES("CTA_0003"),
    CUENTA_NO_ESTA_EN_BANELCO("CTA_0004"),
    CUENTA_ALFA_NO_VERIFICADA("CTA_0005"),
    CUENTA_ALFA_NO_VERIFICADA_NUNCA_OPERO_USD("CTA_0006"),
    DESTINATARIO_NO_PUEDE_RECIBIR_TRANSFERENCIAS("CTA_0007"),
    ERROR_GENERICO_DAO("DAO_0000"),
    ERROR_GENERICO_MANAGER("MANAGER_0000"),

    /*------ERRORES POR CVU CBU/ALIAS---------------------*/
    CTA_SIN_OPERAR_CVU("CTA_SIN_OPERAR_CVU"),
    CTA_SIN_OPERAR_CBU_ALIAS("CTA_SIN_OPERAR_CBU_ALIAS"),
    IMPORTE_LIMITE_CVU("IMPORTE_LIMITE_CVU"),
    IMPORTE_LIMITE_CBU_ALIAS("IMPORTE_LIMITE_CBU_ALIAS"),
    SALDO_INSUFICIENTE_CVU("SALDO_INSUFICIENTE_CVU"),
    SALDO_INSUFICIENTE_CBU_ALIAS("SALDO_INSUFICIENTE_CBU_ALIAS"),
    CTA_CERRADA_CVU("CTA_CERRADA_CVU"),
    CTA_CERRADA_CBU_ALIAS("CTA_CERRADA_CBU_ALIAS"),
    CTA_SIN_DEBITO_NI_ACRED_CVU("CTA_SIN_DEBITO_NI_ACRED_CVU"),
    CTA_SIN_DEBITO_NI_ACRED_CBU_ALIAS("CTA_SIN_DEBITO_NI_ACRED_CBU_ALIAS"),
    CTA_ORIGEN_SIN_BANE_CVU("CTA_ORIGEN_SIN_BANE_CVU"),
    CTA_ORIGEN_SIN_BANE_CBU_ALIAS("CTA_ORIGEN_SIN_BANE_CBU_ALIAS"),
    EXCEDE_LIMITE_USD_BENEF_CVU("EXCEDE_LIMITE_USD_BENEF_CVU"),
    EXCEDE_LIMITE_USD_BENEF_CBU_ALIAS("EXCEDE_LIMITE_USD_BENEF_CBU_ALIAS"),
    HOST_TIME_OUT_CVU("HOST_TIME_OUT_CVU"),
    HOST_TIME_OUT_CBU_ALIAS("HOST_TIME_OUT_CBU_ALIAS"),
    TRANSF_USD_INHABILITADA_CVU("TRANSF_USD_INHABILITADA_CVU"),
    TRANSF_USD_INHABILITADA_CBU_ALIAS("TRANSF_USD_INHABILITADA_CBU_ALIAS"),
    CTA_ALFA_NO_VERIF_NUNCA_OP_USD_CVU("CTA_ALFA_NO_VERIF_NUNCA_OP_USD_CVU"),
    CTA_ALFA_NO_VERIF_NUNCA_OP_USD_CBU_ALIAS("CTA_ALFA_NO_VERIF_NUNCA_OP_USD_CBU_ALIAS"),
    CTA_ALFA_NO_VERIF_CVU("CTA_ALFA_NO_VERIF_CVU"),
    CTA_ALFA_NO_VERIF_CBU_ALIAS("CTA_ALFA_NO_VERIF_CBU_ALIAS"),
    DAO_EXCEPTION_CVU("DAO_EXCEPTION_CVU"),
    DAO_EXCEPTION_CBU_ALIAS("DAO_EXCEPTION_CBU_ALIAS"),
    TRANSFER_ERROR_ALIAS_CBU("TRANSFER_ERROR_ALIAS_CBU"),
    /*---------------------------------------------------------*/

    RECIPIENTS_API_ERROR("RECIPIENTS_API_ERROR");

    private final String codigo;

    DetalleError(String codigo) {

        this.codigo = codigo;

    }

    public String getCodigo() {

        return this.codigo;

    }

}
